### ISSUE TITLE
Is it possible to provide detailed usage instructions

### ISSUE THREAD

**Issue by zjd1988** [zauberzeug/learning_loop_node#10]
Excellent repositorie!!!!
Is possibale to provide a detailed usage of learning_loop_node？

**Comment by denniswittich** [comment]
Hello and thank you. 
Please note that this repository is designed to work with the Zauberzeug Learning Loop. A server application that allows to train and deploy deep learning models as well as collecting and annotating images. If you are interested you may contact us (visit  zauberzeug.com).

**Comment by zjd1988** [comment]
@denniswittich ok,thanks for your reply.
